NAME = libc.a

HEADER = ./

FLAGS = -Wall -Wextra -Werror -c -I

SRC = 	libc_atoi.c \
		libc_bzero.c \
		libc_isallnum.c \
		libc_arrcpy.c \
		libc_arrlen.c \
		libc_isalpha.c \
		libc_isascii.c \
		libc_isdigit.c \
		libc_isprint.c \
		libc_itoa.c \
		libc_lstadd.c \
		



OBJ = ${SRC:c=o}

all: $(NAME)

$(NAME):
		@gcc $(FLAGS) $(HEADER) $(SRC)
		@ar rcs $(NAME) $(OBJ)
		@echo "\033[32mCompiled Executable\033[0m"

clean:
		@/bin/rm -f $(OBJ)
		@echo "\033[32mRemoved Object Files\033[0m"

fclean: clean
		@/bin/rm -f $(NAME)
		@echo "\033[32mRemoved Executable\033[0m"

re: fclean all